ALTER TABLE payment_info RENAME TO tmp_payment_info;
CREATE TABLE payment_info (
    schedule_id,
    ChandaNo,
    Fullname,
    LocalReceipt,
    MonthPaidFor,
    Chanda Aam,
    Chanda Wasiyyat,
    Jalsa Salana,
    Tariki Jadid,
    Waqfi Jadid,
    Welfare Fund,
    Scholarship,
    Maryam Fund,
    Tabligh,
    Zakat,
    Sadakat,
    Fitrana,
    Moaque Donation,
    MTA,
    Centinary Khilafat,
    Wasiyyat_Hissan_Jaidad,
    Miscellaneous,
    SubTotal
);
INSERT INTO payment_info (
    schedule_id,
    ChandaNo,
    Fullname,
    LocalReceipt,
    MonthPaidFor,
    Chanda Aam,
    Chanda Wasiyyat,
    Jalsa Salana,
    Tariki Jadid,
    Waqfi Jadid,
    Welfare Fund,
    Scholarship,
    Maryam Fund,
    Tabligh,
    Zakat,
    Sadakat,
    Fitrana,
    Moaque Donation,
    MTA,
    Centinary Khilafat,
    Wasiyyat_Hissan_Jaidad,
    Miscellaneous,
    SubTotal
) SELECT schedule_id,ChandaNo,Fullname,LocalReceipt,MonthPaidFor,Chanda Aam,Chanda Wasiyyat,
Jalsa Salana,Tariki Jadid,Waqfi Jadid,Welfare Fund,Scholarship,Maryam Fund,Tabligh,Zakat,Sadakat,
Fitrana,Moaque Donation,MTA,Centinary Khilafat,Wasiyyat_Hissan_Jaidad,Miscellaneous,SubTotal
 FROM tmp_payment_info;
DROP TABLE tmp_payment_info;